<?php
/**
 * QR Code service for managing gym member QR codes
 * Supports dual-mode operation with Ben's QR Code Manager plugin
 * UPDATED: Added username lookup support
 */
class Gym_QR_Service
{

    private $email_service;

    public function __construct()
    {
        $this->email_service = new Gym_Email_Service();
    }

    /**
     * Check if Ben's QR Code Manager plugin is active
     */
    public function has_ben_qr_plugin()
    {
        return class_exists('Ben_QR_Code_Manager') || function_exists('ben_qr_get_user_qr_url');
    }

    /**
     * FIXED: Generate a unique 8-digit alphanumeric code
     */
    public function generate_unique_id()
    {
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
        $length = 8;
        $max_attempts = 100; // Prevent infinite loops
        $attempts = 0;

        do {
            $unique_id = '';
            for ($i = 0; $i < $length; $i++) {
                $unique_id .= $characters[wp_rand(0, strlen($characters) - 1)];
            }

            // 🔴 FIX: Check if this ID already exists - but handle WP_Error properly
            $existing_user = $this->lookup_user_by_code($unique_id);
            $id_exists = !is_wp_error($existing_user) && isset($existing_user['user_found']) && $existing_user['user_found'];

            $attempts++;

            // Safety net to prevent infinite loops
            if ($attempts >= $max_attempts) {
                error_log("QR Code generation: Max attempts ({$max_attempts}) reached, using timestamp suffix");
                $unique_id = substr($unique_id, 0, 6) . substr(time(), -2); // Add timestamp suffix
                break;
            }

        } while ($id_exists);

        return $unique_id;
    }

    /**
     * Generate QR code image URL using external service
     */
    public function generate_qr_url($unique_id)
    {
        $base_url = 'https://api.qrserver.com/v1/create-qr-code/';
        $size = Gym_Admin::get_setting('qr_code_size', '300x300');

        return $base_url . '?' . http_build_query(array(
            'size' => $size,
            'data' => $unique_id
        ));
    }

    /**
     * Get existing QR code data for a user
     */
    public function get_user_qr_code($user_id)
    {
        $user = get_user_by('id', $user_id);
        if (!$user) {
            return new WP_Error('user_not_found', 'User not found.');
        }

        $unique_id = get_user_meta($user_id, 'unique_id', true);
        $qr_code_url = get_user_meta($user_id, 'qr_code_url', true);

        $has_qr_code = !empty($unique_id);
        $generated_by = 'unknown';

        // Determine source of QR code
        if ($has_qr_code) {
            if ($this->has_ben_qr_plugin()) {
                // Check if this was generated by Ben's plugin
                $ben_qr_url = function_exists('ben_qr_get_user_qr_url') ? ben_qr_get_user_qr_url($user_id) : null;
                $generated_by = $ben_qr_url ? 'ben_plugin' : 'gym_plugin';
            } else {
                $generated_by = 'gym_plugin';
            }
        }

        return array(
            'success' => true,
            'user_id' => $user_id,
            'unique_id' => $unique_id ?: null,
            'qr_code_url' => $qr_code_url ?: null,
            'has_qr_code' => $has_qr_code,
            'generated_by' => $generated_by
        );
    }

    /**
     * Generate or update QR code for a user
     */
    public function generate_qr_for_user($user_id, $force_regenerate = false)
    {
        $user = get_user_by('id', $user_id);
        if (!$user) {
            return new WP_Error('user_not_found', 'User not found.');
        }

        $existing_unique_id = get_user_meta($user_id, 'unique_id', true);
        $action = empty($existing_unique_id) ? 'created' : 'updated';

        // If user already has a QR code and we're not forcing regeneration
        if (!empty($existing_unique_id) && !$force_regenerate) {
            $existing_qr_url = get_user_meta($user_id, 'qr_code_url', true);

            return array(
                'success' => true,
                'message' => 'User already has QR code',
                'user_id' => $user_id,
                'unique_id' => $existing_unique_id,
                'qr_code_url' => $existing_qr_url,
                'email_sent' => false,
                'action' => 'existing'
            );
        }

        // Check if Ben's plugin is active and should handle this
        if ($this->has_ben_qr_plugin() && function_exists('ben_qr_generate_for_user')) {
            $ben_result = ben_qr_generate_for_user($user_id);
            if (!is_wp_error($ben_result)) {
                return array(
                    'success' => true,
                    'message' => 'QR code generated via Ben\'s plugin',
                    'user_id' => $user_id,
                    'unique_id' => $ben_result['unique_id'],
                    'qr_code_url' => $ben_result['qr_code_url'],
                    'email_sent' => $ben_result['email_sent'],
                    'action' => $action,
                    'generated_by' => 'ben_plugin'
                );
            }
        }

        // Generate QR code using our own system
        $unique_id = $this->generate_unique_id();
        $qr_code_url = $this->generate_qr_url($unique_id);

        // Store in user meta
        update_user_meta($user_id, 'unique_id', $unique_id);
        update_user_meta($user_id, 'qr_code_url', $qr_code_url);

        // Store generation timestamp and source
        update_user_meta($user_id, 'qr_generated_at', current_time('mysql'));
        update_user_meta($user_id, 'qr_generated_by', 'gym_plugin');

        // Send email notification
        $email_sent = false;
        $email_enabled = Gym_Admin::get_setting('qr_email_notifications', '1') === '1';

        if ($email_enabled) {
            $email_result = $this->send_qr_notification($user_id, $action);
            $email_sent = !is_wp_error($email_result);
        }

        return array(
            'success' => true,
            'message' => 'QR code generated successfully',
            'user_id' => $user_id,
            'unique_id' => $unique_id,
            'qr_code_url' => $qr_code_url,
            'email_sent' => $email_sent,
            'action' => $action,
            'generated_by' => 'gym_plugin'
        );
    }
    /**
     * 🆕 UPDATED: Find user by QR code, username, email, OR phone number
     * Supports quad lookup mode - tries QR code, username, email, then phone
     */
    public function lookup_user_by_code($unique_id)
    {
        if (empty($unique_id)) {
            return new WP_Error('empty_code', 'Search term cannot be empty.');
        }

        global $wpdb;
        $lookup_method = null;
        $user_id = null;

        // STEP 1: Try QR code lookup first
        $user_id = $wpdb->get_var($wpdb->prepare(
            "SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key = 'unique_id' AND meta_value = %s LIMIT 1",
            $unique_id
        ));

        if ($user_id) {
            $lookup_method = 'qr_code';
        } else {
            // STEP 2: Try username/login lookup
            $user = get_user_by('login', $unique_id);
            if ($user) {
                $user_id = $user->ID;
                $lookup_method = 'username';
            } else {
                // STEP 3: Try email lookup
                $user = get_user_by('email', $unique_id);
                if ($user) {
                    $user_id = $user->ID;
                    $lookup_method = 'email';
                } else {
                    // STEP 4: Try phone lookup
                    $user_id = $wpdb->get_var($wpdb->prepare(
                        "SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key = 'phone' AND meta_value = %s LIMIT 1",
                        $unique_id
                    ));

                    if ($user_id) {
                        $lookup_method = 'phone';
                    } else {
                        // Not found by any method
                        return new WP_Error('user_not_found', 'No user found with this QR code, username, email, or phone number.');
                    }
                }
            }
        }

        // Get user object
        $user = get_user_by('id', $user_id);
        if (!$user) {
            return new WP_Error('user_not_found', 'User data not found.');
        }

        // Get the user's actual QR code (in case they were found by username/email/phone)
        $actual_unique_id = get_user_meta($user_id, 'unique_id', true);

        // Get membership information
        $membership_service = new Gym_Membership_Service();
        $membership = $membership_service->get_user_membership($user_id);

        return array(
            'success' => true,
            'user_found' => true,
            'lookup_method' => $lookup_method, // 'qr_code', 'username', 'email', or 'phone'
            'search_term' => $unique_id,
            'user' => array(
                'id' => $user->ID,
                'username' => $user->user_login,
                'name' => $user->display_name,
                'email' => $user->user_email,
                'first_name' => get_user_meta($user_id, 'first_name', true),
                'last_name' => get_user_meta($user_id, 'last_name', true),
                'phone' => get_user_meta($user_id, 'phone', true),
                'membership' => array(
                    'plan' => $membership['level_name'] ?? 'No Membership',
                    'status' => $membership['status'] ?? 'inactive',
                    'expiry_date' => $membership['expiry_date'] ?? null
                ),
                'unique_id' => $actual_unique_id ?: null
            )
        );
    }

    /**
     * Send QR code notification email to user
     */
    public function send_qr_notification($user_id, $action = 'generated')
    {
        $user = get_user_by('id', $user_id);
        if (!$user) {
            return new WP_Error('user_not_found', 'User not found.');
        }

        $unique_id = get_user_meta($user_id, 'unique_id', true);
        $qr_code_url = get_user_meta($user_id, 'qr_code_url', true);

        if (empty($unique_id)) {
            return new WP_Error('no_qr_code', 'User has no QR code to send.');
        }

        // Prepare email data
        $custom_data = array(
            'unique_id' => $unique_id,
            'qr_code_image' => '<div style="text-align: center; margin: 20px 0;"><img src="' . esc_url($qr_code_url) . '" alt="Your QR Code" style="max-width: 200px;"></div>',
            'qr_action' => $action === 'created' ? 'generated' : 'updated'
        );

        // Use custom email instead of template since we need QR-specific content
        $subject = 'Your Gym Access Code - {{gym_name}}';
        $content = $this->get_qr_email_template();

        // Send email using email service's custom email method
        return $this->email_service->send_custom_email($user_id, $subject, $content, $custom_data);
    }

    /**
     * Get QR code email template content
     */
    private function get_qr_email_template()
    {
        $template_file = SIMPLE_GYM_ADMIN_PLUGIN_DIR . 'templates/qr-code-email.html';

        if (file_exists($template_file)) {
            return file_get_contents($template_file);
        }

        // Return default template if file doesn't exist
        return '
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #333;">Your Gym Access Code</h2>
            <p>Hi {{user_name}},</p>
            <p>Your unique gym access code has been {{qr_action}}.</p>
            <div style="background: #f9f9f9; padding: 20px; margin: 20px 0; text-align: center;">
                <h3>Your Unique Access Code</h3>
                <p style="font-size: 24px; font-weight: bold; letter-spacing: 2px; color: #333;">{{unique_id}}</p>
                {{qr_code_image}}
            </div>
            <p><strong>How to use:</strong></p>
            <ul>
                <li>Show this QR code at gym entry</li>
                <li>Or provide your unique ID: <strong>{{unique_id}}</strong></li>
                <li>Save this email for easy access</li>
            </ul>
            <p>If you have any questions, please contact us.</p>
            <p>Best regards,<br>{{gym_name}} Team</p>
        </div>';
    }

    /**
     * Search users by QR code (partial matching)
     */
    public function search_users_by_qr_code($search_term, $limit = 20, $offset = 0)
    {
        if (empty($search_term)) {
            return array(
                'users' => array(),
                'total' => 0,
                'message' => 'Search term cannot be empty'
            );
        }

        global $wpdb;

        // Search for users with QR codes matching the search term
        $search_like = '%' . $wpdb->esc_like($search_term) . '%';

        $query = "
            SELECT u.ID, u.display_name, u.user_email, um.meta_value as unique_id
            FROM {$wpdb->users} u
            JOIN {$wpdb->usermeta} um ON u.ID = um.user_id
            WHERE um.meta_key = 'unique_id' 
            AND um.meta_value LIKE %s
            ORDER BY u.display_name
            LIMIT %d OFFSET %d
        ";

        $users = $wpdb->get_results($wpdb->prepare($query, $search_like, $limit, $offset));

        // Get total count
        $total_query = "
            SELECT COUNT(DISTINCT u.ID)
            FROM {$wpdb->users} u
            JOIN {$wpdb->usermeta} um ON u.ID = um.user_id
            WHERE um.meta_key = 'unique_id' 
            AND um.meta_value LIKE %s
        ";

        $total = $wpdb->get_var($wpdb->prepare($total_query, $search_like));

        // Format results
        $formatted_users = array();
        foreach ($users as $user) {
            $membership_service = new Gym_Membership_Service();
            $membership = $membership_service->get_user_membership($user->ID);

            $formatted_users[] = array(
                'id' => $user->ID,
                'name' => $user->display_name,
                'email' => $user->user_email,
                'unique_id' => $user->unique_id,
                'membership' => array(
                    'plan' => $membership['level_name'] ?? 'No Membership',
                    'status' => $membership['status'] ?? 'inactive'
                )
            );
        }

        return array(
            'users' => $formatted_users,
            'total' => (int) $total,
            'limit' => $limit,
            'offset' => $offset
        );
    }

    /**
     * Auto-generate QR codes for users without them
     */
    public function auto_generate_missing_qr_codes($batch_size = 50)
    {
        global $wpdb;

        // Find users without QR codes
        $query = "
            SELECT u.ID
            FROM {$wpdb->users} u
            LEFT JOIN {$wpdb->usermeta} um ON u.ID = um.user_id AND um.meta_key = 'unique_id'
            WHERE um.meta_value IS NULL OR um.meta_value = ''
            LIMIT %d
        ";

        $user_ids = $wpdb->get_col($wpdb->prepare($query, $batch_size));

        $results = array(
            'processed' => 0,
            'generated' => 0,
            'errors' => array()
        );

        foreach ($user_ids as $user_id) {
            $results['processed']++;

            $result = $this->generate_qr_for_user($user_id);

            if (is_wp_error($result)) {
                $results['errors'][] = array(
                    'user_id' => $user_id,
                    'error' => $result->get_error_message()
                );
            } else {
                $results['generated']++;
            }
        }

        return $results;
    }

    /**
     * Get QR code statistics
     */
    public function get_qr_statistics()
    {
        global $wpdb;

        $total_users = $wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->users}");

        $users_with_qr = $wpdb->get_var("
            SELECT COUNT(DISTINCT user_id) 
            FROM {$wpdb->usermeta} 
            WHERE meta_key = 'unique_id' 
            AND meta_value != ''
        ");

        $recent_qr_generated = $wpdb->get_var($wpdb->prepare("
            SELECT COUNT(DISTINCT user_id) 
            FROM {$wpdb->usermeta} 
            WHERE meta_key = 'qr_generated_at' 
            AND meta_value > %s
        ", date('Y-m-d H:i:s', strtotime('-7 days'))));

        return array(
            'total_users' => (int) $total_users,
            'users_with_qr' => (int) $users_with_qr,
            'users_without_qr' => $total_users - $users_with_qr,
            'coverage_percentage' => $total_users > 0 ? round(($users_with_qr / $total_users) * 100, 2) : 0,
            'recent_generated' => (int) $recent_qr_generated,
            'ben_plugin_active' => $this->has_ben_qr_plugin()
        );
    }

    /**
     * Cleanup orphaned QR codes (codes without valid users)
     */
    public function cleanup_orphaned_qr_codes()
    {
        global $wpdb;

        $deleted = $wpdb->query("
            DELETE um FROM {$wpdb->usermeta} um
            LEFT JOIN {$wpdb->users} u ON um.user_id = u.ID
            WHERE u.ID IS NULL 
            AND (um.meta_key = 'unique_id' OR um.meta_key = 'qr_code_url' OR um.meta_key = 'qr_generated_at')
        ");

        return array(
            'success' => true,
            'deleted_records' => $deleted
        );
    }
}